### ISSUE TITLE
--all-regions-with-lang ignoring parent-clone data

### ISSUE THREAD

**Issue by HVR88** [andrebrait/1g1r-romset-generator#14] opened 2020-04-16 16:22 UTC
I'm using a version downloaded sometime last month - this might be fixed in the new version, I'll have to check later.

**Issue:**
When using the --all-regions-with-lang option the tool is allowing clones of an already accepted file to pass.

**Example/Procedure to Duplicate Issue**

Using SNES parent-clone DAT from DAT-O-Matic

Commandline arguments:

python3 generate.py -r USA,EUR -l en -e zip --all-regions-with-lang --prefer-parents --no-bios --no-program --no-enhancement-chip --no-beta --no-demo --no-sample --no-promo -d "SNES.dat" -i ../PATHIN -o ../PATHOUT

**What I expect to happen**

Files are grabbed in priority USA and then Europe and must have English Language - no clones. Files that are not included by this priority (from other regions) but have English language, should also be included.

"Not included" must account for being a clone of an already included title.

**What is actually happening**

Clones of titles already selected in the original priority are also included

**Specific File Results**

I get both Hebereke's Popoon from Europe  AND Hebereke no Popoon from Japan.  (And others like this)

**Comment by HVR88** [comment] 2020-04-16 16:26
Note: JPN was not included on the original priority list which is expected to work. I can test with JPN also specified to see if it makes a difference and helps find the root cause of this issue.

**Comment by andrebrait** [comment] 2020-04-16 18:41
Huh, weird.
At least with the latest SNES dat, I can't reproduce it.

I get the ones below:
```
Hebereke's Popoitto (Europe).zip
Hebereke's Popoon (Europe).zip
```

Could you download the latest version (1.9.0) and try it to see how it goes?

It's also going to use a much more accurate way of detecting the ROMs, though it will take a bit longer to process (but you can use the old way by adding `--no-scan` to the command).

**Comment by HVR88** [comment] 2020-04-16 18:58
Thanks for looking at this so quickly!  I was planning to do a brand new filtering pass on my datable consoles, so I'm happy to try the latest version.

Let me see if I can attach or paste the dat I used. If there are any issues, I'll put it up for download somewhere.

**Comment by HVR88** [comment] 2020-04-16 19:00
OK, dat won't attach as the maximum comment is 64KB and the file is over 1MB. :)  You can download it here: https://salumba.com/SNES.dat

**Comment by andrebrait** [comment] 2020-04-16 19:28
Yeah, I still get the same ROMs with your dat. Let me know if it works.

**Comment by HVR88** [comment] 2020-04-16 19:33
I just downloaded a few minutes ago - how can I check the version?

**Comment by andrebrait** [comment] 2020-04-16 19:35
```
python3 generate.py -v
```

:-)

**Comment by andrebrait** [comment] 2020-04-16 19:36
If the version is >1.9.0, that is. Because I just introduced that

**Comment by HVR88** [comment] 2020-04-16 19:39
OK, because I had already tried that. :)  I was worried I didn't move the files over to my server.

**Comment by HVR88** [comment] 2020-04-16 19:59
Seems to work as expected now and omits the Japanese clones I noticed earlier.

**Comment by andrebrait** [comment] 2020-04-17 06:29
Ok, I'm closing this then :+1:

**Closed by andrebrait** 2020-04-17 06:29 UTC
